/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_juav_jni_HalLinuxNative */

#ifndef _Included_ub_cse_juav_jni_HalLinuxNative
#define _Included_ub_cse_juav_jni_HalLinuxNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_juav_jni_HalLinuxNative
 * Method:    nativeHalLinuxShouldExit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_HalLinuxNative_nativeHalLinuxShouldExit
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_HalLinuxNative
 * Method:    nativeHalLinuxInitializationPriorToControlLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_HalLinuxNative_nativeHalLinuxInitializationPriorToControlLoop
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_HalLinuxNative
 * Method:    nativeHalLinuxAfterShouldExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_HalLinuxNative_nativeHalLinuxAfterShouldExit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
