/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_juav_jni_HalSitlNative */

#ifndef _Included_ub_cse_juav_jni_HalSitlNative
#define _Included_ub_cse_juav_jni_HalSitlNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_juav_jni_HalSitlNative
 * Method:    nativeInitizationPriorToControlLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_HalSitlNative_nativeInitizationPriorToControlLoop
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_HalSitlNative
 * Method:    nativeHalSitlInnerLoopAfterCallBacks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_HalSitlNative_nativeHalSitlInnerLoopAfterCallBacks
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_HalSitlNative
 * Method:    getHalSitlSchedulerShouldReboot
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_HalSitlNative_getHalSitlSchedulerShouldReboot
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_HalSitlNative
 * Method:    getHalSitlSchedulerShouldExit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_HalSitlNative_getHalSitlSchedulerShouldExit
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_HalSitlNative
 * Method:    sitlFillStackNan
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_HalSitlNative_sitlFillStackNan
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
