/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_juav_jni_ArdupilotNative */

#ifndef _Included_ub_cse_juav_jni_ArdupilotNative
#define _Included_ub_cse_juav_jni_ArdupilotNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeApSchedulerPriorToFastLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeApSchedulerPriorToFastLoop
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeApSchedulerPostToFastLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeApSchedulerPostToFastLoop
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    setHalUtilPersistentDataSchedulerTask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_setHalUtilPersistentDataSchedulerTask
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeApSchedulerGetLoopPeriodS
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeApSchedulerGetLoopPeriodS
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeFastLoopBeforeAttitudeController
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeFastLoopBeforeAttitudeController
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    surfaceTracingInvalidateForLogging
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_surfaceTracingInvalidateForLogging
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    getFlightModeNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_ArdupilotNative_getFlightModeNumber
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    callNativeFlightMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_callNativeFlightMode
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeFastLoopAfterAttitudeController
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeFastLoopAfterAttitudeController
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeRunBeforeStabilizationCallAttitudeController
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeRunBeforeStabilizationCallAttitudeController
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeRunAfterStabilizationCallAttitudeController
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeRunAfterStabilizationCallAttitudeController
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    getStabilizationModeTargetYawRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_getStabilizationModeTargetYawRate
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    getStabilizationModeTargetPitch
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_getStabilizationModeTargetPitch
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    getStabilizationModeTargetRoll
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_getStabilizationModeTargetRoll
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    getAttitudeTargetQuat
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_ub_cse_juav_jni_ArdupilotNative_getAttitudeTargetQuat
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetAttitudeTargetEulerAngle
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetAttitudeTargetEulerAngle
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetAttitudeTargetEulerRate
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetAttitudeTargetEulerRate
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetAttitudeTargetAngVel
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetAttitudeTargetAngVel
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetRateBfFfEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetRateBfFfEnabled
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetAccelRollMax
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetAccelRollMax
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetAccelPitchMax
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetAccelPitchMax
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetAccelYawMax
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetAccelYawMax
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetAttitudeInputTc
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetAttitudeInputTc
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeAttitudeGetDt
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeAttitudeGetDt
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetAngVelRollMax
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetAngVelRollMax
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetAngVelPitchMax
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetAngVelPitchMax
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetAngVelYawMax
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetAngVelYawMax
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeSetAttitudeTargetQuat
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeSetAttitudeTargetQuat
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeSetAttitudeTargetEulerAngle
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeSetAttitudeTargetEulerAngle
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeSetAttitudeTargetEulerRate
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeSetAttitudeTargetEulerRate
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeSetAttitudeTargetAngVel
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeSetAttitudeTargetAngVel
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetRateTargetAngVel
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetRateTargetAngVel
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetAttitudeThrustErrorAngle
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetAttitudeThrustErrorAngle
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    getAhrsGetQuatBodyToNed
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_ub_cse_juav_jni_ArdupilotNative_getAhrsGetQuatBodyToNed
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeSetAttitudeThrustAngle
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeSetAttitudeThrustAngle
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeAttitudeGetPAngleYawKp
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeAttitudeGetPAngleYawKp
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeAttitudeGetPAngleRollKp
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeAttitudeGetPAngleRollKp
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeAttitudeGetPAnglePitchKp
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeAttitudeGetPAnglePitchKp
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeAttitudeUseSqrtController
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeAttitudeUseSqrtController
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeAttitudeGetAhrsGyro
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeAttitudeGetAhrsGyro
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeSetAttitudeFeedForwardScalar
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeSetAttitudeFeedForwardScalar
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGetAttitudeFeedForwardScalar
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGetAttitudeFeedForwardScalar
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeSetAttitudeAngError
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeSetAttitudeAngError
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeAttitudeSetRateTargetAngVel
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeAttitudeSetRateTargetAngVel
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeAttitudeSetThrustErrorAngle
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeAttitudeSetThrustErrorAngle
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeAttitudeGetSlewYaw
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeAttitudeGetSlewYaw
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeSetAPVehicleSchedulerGDt
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeSetAPVehicleSchedulerGDt
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeModeRtlIsMotorsArmed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeModeRtlIsMotorsArmed
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeModeRtlIsStateComplete
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeModeRtlIsStateComplete
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    runAttitudeControllerQuatTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_runAttitudeControllerQuatTest
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    inputEulerAngleRollPitchEulerRateYaw
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_inputEulerAngleRollPitchEulerRateYaw
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeLoiterRunPriorToAttitudeControl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeLoiterRunPriorToAttitudeControl
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeLoiterRunAfterAttitudeControl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeLoiterRunAfterAttitudeControl
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeLoiterGetTargetYawRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeLoiterGetTargetYawRate
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeLoiterGetTargetPitch
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeLoiterGetTargetPitch
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeLoiterGetTargetRoll
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeLoiterGetTargetRoll
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetMode
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedTakeoffRun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedTakeoffRun
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedPosControlRunPriorToAttitude
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedPosControlRunPriorToAttitude
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetAutoYawMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetAutoYawMode
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetWpNavRoll
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetWpNavRoll
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetWpNavPitch
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetWpNavPitch
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetTargetYawRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetTargetYawRate
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetAutoYawRateCds
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetAutoYawRateCds
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetAutoYawYaw
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetAutoYawYaw
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedVelControlRunPriorToAttitude
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedVelControlRunPriorToAttitude
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetPosControlRoll
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetPosControlRoll
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetPosControlPitch
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetPosControlPitch
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedPosVelControlRunPriorToAttitude
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedPosVelControlRunPriorToAttitude
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedAngleControlRunPriorToAttitude
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedAngleControlRunPriorToAttitude
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetAngleControlRunRollIn
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetAngleControlRunRollIn
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetAngleControlRunPitchIn
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetAngleControlRunPitchIn
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedIsAngleStateUseYawRate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedIsAngleStateUseYawRate
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetAngleControlRunYawRateIn
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetAngleControlRunYawRateIn
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedGetAngleControlRunYawIn
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedGetAngleControlRunYawIn
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_ArdupilotNative
 * Method:    nativeGuidedAngleControlRunAfterAttitude
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_ArdupilotNative_nativeGuidedAngleControlRunAfterAttitude
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
