/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_jni_image_OpenCv2Wrapper */

#ifndef _Included_ub_cse_jni_image_OpenCv2Wrapper
#define _Included_ub_cse_jni_image_OpenCv2Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_jni_image_OpenCv2Wrapper
 * Method:    setBinerizeThreshold
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ub_cse_jni_image_OpenCv2Wrapper_setBinerizeThreshold
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ub_cse_jni_image_OpenCv2Wrapper
 * Method:    initializeCamera
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_jni_image_OpenCv2Wrapper_initializeCamera
  (JNIEnv *, jobject);

/*
 * Class:     ub_cse_jni_image_OpenCv2Wrapper
 * Method:    pullWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_jni_image_OpenCv2Wrapper_pullWidth
  (JNIEnv *, jobject);

/*
 * Class:     ub_cse_jni_image_OpenCv2Wrapper
 * Method:    pullHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_jni_image_OpenCv2Wrapper_pullHeight
  (JNIEnv *, jobject);

/*
 * Class:     ub_cse_jni_image_OpenCv2Wrapper
 * Method:    takePicture
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_jni_image_OpenCv2Wrapper_takePicture
  (JNIEnv *, jobject);

/*
 * Class:     ub_cse_jni_image_OpenCv2Wrapper
 * Method:    loadImageFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_jni_image_OpenCv2Wrapper_loadImageFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ub_cse_jni_image_OpenCv2Wrapper
 * Method:    getBinerizeValue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ub_cse_jni_image_OpenCv2Wrapper_getBinerizeValue
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ub_cse_jni_image_OpenCv2Wrapper
 * Method:    getCentroidX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_jni_image_OpenCv2Wrapper_getCentroidX
  (JNIEnv *, jobject);

/*
 * Class:     ub_cse_jni_image_OpenCv2Wrapper
 * Method:    getCentroidY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_jni_image_OpenCv2Wrapper_getCentroidY
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
