/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_jni_image_ImageCameraWrapper */

#ifndef _Included_ub_cse_jni_image_ImageCameraWrapper
#define _Included_ub_cse_jni_image_ImageCameraWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_jni_image_ImageCameraWrapper
 * Method:    initializeCamera
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_jni_image_ImageCameraWrapper_initializeCamera
  (JNIEnv *, jobject);

/*
 * Class:     ub_cse_jni_image_ImageCameraWrapper
 * Method:    pullWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_jni_image_ImageCameraWrapper_pullWidth
  (JNIEnv *, jobject);

/*
 * Class:     ub_cse_jni_image_ImageCameraWrapper
 * Method:    pullHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_jni_image_ImageCameraWrapper_pullHeight
  (JNIEnv *, jobject);

/*
 * Class:     ub_cse_jni_image_ImageCameraWrapper
 * Method:    takePicture
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_jni_image_ImageCameraWrapper_takePicture
  (JNIEnv *, jobject);

/*
 * Class:     ub_cse_jni_image_ImageCameraWrapper
 * Method:    readPixelRed
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ub_cse_jni_image_ImageCameraWrapper_readPixelRed
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ub_cse_jni_image_ImageCameraWrapper
 * Method:    readPixelGreen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ub_cse_jni_image_ImageCameraWrapper_readPixelGreen
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ub_cse_jni_image_ImageCameraWrapper
 * Method:    readPixelBlue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ub_cse_jni_image_ImageCameraWrapper_readPixelBlue
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
